# https://pre-commit.com
default_language_version:
  python: python3
default_stages: [pre-commit, manual]
fail_fast: true
exclude: "(received/|.*_depr)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: check-added-large-files
      #   args: ['--maxkb=65536']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck --check-sourced --shell=bash --exclude=SC1087
        language: system
        types: [shell]
      # - id: pydocstyle
      #   name: pydocstyle
      #   entry: pydocstyle
      #   language: system
      #   types: [python]
      #   exclude: "(^experiments/|.*_depr)"
      # - id: flake8
      #   name: flake8
      #   entry: flake8
      #   language: system
      #   types: [python]
      #   exclude: "(^tasks/|.*_depr)"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]
  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: v1.0.3
    hooks:
      - id: auto-smart-commit
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: ["--fix"] 
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
