class RdmCollection:
    def __init__(self, **metadata):
        self.id = metadata.get("collectionId")
        self.title = metadata.get("title")
        self.feature_count = metadata.get("featureCount")
        self.data_type = metadata.get("type")
        self.access_type = metadata.get("accessType")
        self.observation_method = metadata.get("typeOfObservationMethod")
        self.confidence_lc = metadata.get("confidenceLandCover")
        self.confidence_ct = metadata.get("confidenceCropType")
        self.confidence_irr = metadata.get("confidenceIrrigationType")
        self.ewoc_codes = metadata.get("ewocCodes")
        self.irr_codes = metadata.get("irrTypes")
        self.spatial_extent = metadata.get("extent")["spatial"]
        self.temporal_extent = metadata.get("extent")["temporal"]["interval"][0]
        self.additional_data = metadata.get("additionalData")
        self.crs = metadata.get("crs")
        self.last_modified = metadata.get("lastModificationTime")
        self.last_modified_by = metadata.get("lastModifierId")
        self.creation_time = metadata.get("creationTime")
        self.created_by = metadata.get("creatorId")
        self.fid = metadata.get("id")
